services:
  nats:
    image: nats:latest
    container_name: nats-jetstream
    command: -js
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data

  argus-db:
    image: postgres:18.1-alpine3.23
    container_name: banco-argus-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-argus-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DB:-argus-post-db}
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U argus-user -d argus-post-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  argus-cache:
    image: redis:8.4.0-alpine
    container_name: argus-cache
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  argus-meili:
    image: getmeili/meilisearch:v1.33.1
    container_name: argus-search
    ports: 
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=masterKey123
      - MEILI_ENV=development
    restart: unless-stopped

volumes:
  postgres_data:
  nats_data:
  redis_data:
  meili_data:
  argus_temp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/tmp_data